import json
import os
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from nexkit import agent
from tests.support import FakeClaude, GitRepos, git, make_config

CONTEXT = {
    "issue": 5,
    "pr": "",
    "title": "Fix add",
    "body": "add() subtracts. Use $HOME and ${{ secrets.X }} literally.",
    "discussion": "No discussion.",
    "plan": "Change add to return a + b.",
    "note": "None.",
    "feedback": "",
}
DONE = {"status": "done", "summary": "Fixed add.", "blocker": "", "checks_run": ["make test"]}


class PromptTests(unittest.TestCase):
    def test_prompt_keeps_untrusted_text_literal(self):
        prompt = agent.build_prompt("implement", CONTEXT, make_config())
        self.assertIn("Use $HOME and ${{ secrets.X }} literally.", prompt)
        self.assertIn("`test`: `true`", prompt)
        self.assertIn("`.github/`", prompt)
        self.assertNotIn("$plan", prompt)

    def test_every_stage_template_is_complete(self):
        extra = {"diff": "+x", "check_results": "ok"}
        for stage in ("plan", "implement", "fix", "review"):
            prompt = agent.build_prompt(stage, CONTEXT, make_config(), extra)
            for name in ("$issue", "$title", "$plan", "$checks", "$protected", "$diff"):
                self.assertNotIn(name, prompt, f"{stage} leaves {name}")

    def test_command_restricts_read_only_stages(self):
        cfg = make_config(
            effort="high", stages={"implement": {"max_budget_usd": 5, "model": "opus"}}
        )
        plan = agent.claude_command("plan", cfg)
        self.assertIn("Read,Grep,Glob", plan)
        self.assertNotIn("bypassPermissions", plan)
        fix = agent.claude_command("fix", cfg)
        self.assertIn("bypassPermissions", fix)
        self.assertEqual(fix[fix.index("--model") + 1], "opus")
        self.assertEqual(fix[fix.index("--max-budget-usd") + 1], "5")
        self.assertEqual(fix[fix.index("--effort") + 1], "high")
        schema = json.loads(fix[fix.index("--json-schema") + 1])
        self.assertIn("status", schema["required"])


class InterpretTests(unittest.TestCase):
    def run_result(self, event=None, **kw):
        return {
            "event": event,
            "returncode": 0,
            "timed_out": False,
            "stderr": "",
            "seconds": 1.0,
            **kw,
        }

    def test_outcomes(self):
        ok = {"subtype": "success", "structured_output": DONE, "total_cost_usd": 1.5}
        self.assertEqual(agent.interpret("implement", self.run_result(ok), 5)["status"], "done")
        blocked = {**ok, "structured_output": {**DONE, "status": "blocked", "blocker": "No spec"}}
        result = agent.interpret("implement", self.run_result(blocked), 5)
        self.assertEqual((result["status"], result["error"]), ("blocked", "No spec"))
        timeout = agent.interpret("plan", self.run_result(ok, timed_out=True), 7)
        self.assertIn("7 minutes", timeout["error"])
        missing = agent.interpret("plan", self.run_result(None, stderr="auth failed"), 5)
        self.assertIn("auth failed", missing["error"])
        budget = agent.interpret(
            "plan", self.run_result({"subtype": "error_max_budget_usd", "is_error": True}), 5
        )
        self.assertIn("error_max_budget_usd", budget["error"])
        unstructured = agent.interpret("review", self.run_result({"subtype": "success"}), 5)
        self.assertIn("structured result", unstructured["error"])


class RunStageTests(unittest.TestCase):
    def setUp(self):
        self.repos = GitRepos()
        self.repo = self.repos.clone("work")
        self.tmp = tempfile.TemporaryDirectory()
        self.out = Path(self.tmp.name) / "out"
        self.claude = FakeClaude(self.tmp.name)

    def tearDown(self):
        self.claude.restore()
        self.tmp.cleanup()
        self.repos.cleanup()

    def run_stage(self, stage, **kw):
        return agent.run_stage(
            stage, CONTEXT, make_config(), self.repo, self.out, claude=str(self.claude.path), **kw
        )

    def test_implement_collects_only_agent_changes(self):
        # Setup side effects (tracked or not) must not appear in the patch.
        (self.repo / "setup-output.txt").write_text("generated by npm install\n")
        start = git(self.repo, "rev-parse", "HEAD")
        self.claude.configure(
            result=DONE,
            write={
                "calc.py": "def add(a, b):\n    return a + b\n",
                "ignored/x": "1",
                "__pycache__/calc.cpython-312.pyc": "x",
                "web/node_modules/pkg/index.js": "x",
            },
        )
        result = self.run_stage("implement")
        self.assertEqual(result["status"], "done")
        self.assertEqual(result["changed_files"], ["calc.py"])
        self.assertEqual(result["start_head"], start)
        self.assertEqual(result["cost"], 0.5)
        patch = (self.out / "changes.patch").read_text()
        self.assertIn("+    return a + b", patch)
        self.assertNotIn("setup-output", patch)
        saved = json.loads((self.out / "result.json").read_text())
        self.assertEqual(saved["status"], "done")
        self.assertTrue((self.out / "transcript.jsonl").read_text())
        call = self.claude.call()
        self.assertEqual(Path(call["cwd"]).resolve(), self.repo.resolve())
        self.assertIn("Change add to return a + b.", call["prompt"])

    def test_no_change_is_an_error(self):
        self.claude.configure(result=DONE)
        result = self.run_stage("implement")
        self.assertEqual(result["status"], "error")
        self.assertIn("without changing", result["error"])

    def test_blocked_agent_publishes_nothing(self):
        self.claude.configure(
            result={**DONE, "status": "blocked", "blocker": "Needs a decision"},
            write={"calc.py": "partial"},
        )
        result = self.run_stage("implement")
        self.assertEqual(result["status"], "blocked")
        self.assertFalse((self.out / "changes.patch").exists())

    def test_review_includes_diff_and_checks(self):
        git(self.repo, "checkout", "-q", "-b", "nexkit/issue-5")
        (self.repo / "calc.py").write_text("def add(a, b):\n    return a + b\n")
        git(self.repo, "add", "-A")
        self.repos.commit(self.repo, "fix")
        verdict = {"verdict": "approve", "summary": "Good", "criteria": [], "findings": []}
        self.claude.configure(result=verdict)
        checks = [{"name": "test", "run": "true", "exit_code": 0, "passed": True, "output": ""}]
        result = self.run_stage("review", checks=checks, base="main")
        self.assertEqual(result["status"], "done")
        prompt = self.claude.call()["prompt"]
        self.assertIn("+    return a + b", prompt)
        self.assertIn("`test` (`true`): passed", prompt)

    def test_missing_credentials(self):
        self.claude.configure(result=DONE)
        env = {"CLAUDE_CODE_OAUTH_TOKEN": "", "ANTHROPIC_API_KEY": "", "GITHUB_ACTIONS": "true"}
        with mock.patch.dict(os.environ, env):
            result = self.run_stage("plan")
        self.assertEqual(result["status"], "error")
        self.assertIn("No Claude credential", result["error"])

    def test_timeout_kills_claude(self):
        self.claude.configure(result=DONE, sleep=30)
        run = agent.run_claude(
            "x",
            [str(self.claude.path)],
            cwd=self.repo,
            timeout_seconds=1,
            transcript=Path(self.tmp.name) / "t.jsonl",
        )
        self.assertTrue(run["timed_out"])
        self.assertLess(run["seconds"], 15)


if __name__ == "__main__":
    unittest.main()
